//
// NNUE evaluation, see nnue.h.
//

#include "nnue.h"

#include <algorithm>
#include <cstring>
#include <fstream>
#include <memory>
#include <vector>

// Generated by CMake from nnue/wombat.nnue (see CMakeLists.txt)
extern const unsigned char NNUE_EMBEDDED_DATA[];
extern const size_t NNUE_EMBEDDED_SIZE;

namespace nnue {

namespace {

constexpr size_t FILE_SIZE = sizeof(int16_t) * (INPUTS * HIDDEN + HIDDEN + 2 * HIDDEN) + sizeof(int32_t);

std::unique_ptr<Network> net;

bool load_bytes(const unsigned char *data, size_t size) {
    if (size != FILE_SIZE) return false;
    auto n = std::make_unique<Network>();
    size_t off = 0;
    auto read = [&](void *dst, size_t bytes) {
        std::memcpy(dst, data + off, bytes);
        off += bytes;
    };
    read(n->feature_weights, sizeof(n->feature_weights));
    read(n->feature_bias, sizeof(n->feature_bias));
    read(n->output_weights, sizeof(n->output_weights));
    read(&n->output_bias, sizeof(n->output_bias));
    net = std::move(n);
    return true;
}

inline int feature(Color perspective, Piece pc, Square sq) {
    int relative = color_of(pc) == perspective ? 0 : 1;
    int s = perspective == WHITE ? int(sq) : int(sq) ^ 56;
    return relative * 384 + type_of(pc) * 64 + s;
}

inline const int16_t *row(Color perspective, Piece pc, Square sq) {
    return &net->feature_weights[feature(perspective, pc, sq) * HIDDEN];
}

struct Change {
    Piece piece;
    Square square;
};

} // namespace

bool load_default() { return load_bytes(NNUE_EMBEDDED_DATA, NNUE_EMBEDDED_SIZE); }

bool load(const std::string &path) {
    std::ifstream file(path, std::ios::binary);
    if (!file) return false;
    std::vector<unsigned char> bytes((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
    return load_bytes(bytes.data(), bytes.size());
}

bool loaded() { return net != nullptr; }

void refresh(Accumulator &acc, const Position &p) {
    for (Color c: {WHITE, BLACK}) {
        int16_t *v = acc.values[c];
        std::memcpy(v, net->feature_bias, sizeof(net->feature_bias));
        for (int sq = 0; sq < 64; ++sq) {
            Piece pc = p.at(Square(sq));
            if (pc == NO_PIECE) continue;
            const int16_t *w = row(c, pc, Square(sq));
            for (int i = 0; i < HIDDEN; ++i) v[i] += w[i];
        }
    }
}

void update(const Accumulator &parent, Accumulator &child, const Position &before, Move m) {
    Change add[2], sub[2];
    int n_add = 0, n_sub = 0;

    const Square from = m.from(), to = m.to();
    const Piece moving = before.at(from);
    const Color us = color_of(moving);
    const MoveFlags flags = m.flags();

    switch (flags) {
        case OO:
        case OOO: {
            // surge encodes castling as king-takes-rook for OO, and e1c1 for OOO
            const bool white = from == e1;
            const Square king_to = flags == OO ? (white ? g1 : g8) : (white ? c1 : c8);
            const Square rook_from = flags == OO ? (white ? h1 : h8) : (white ? a1 : a8);
            const Square rook_to = flags == OO ? (white ? f1 : f8) : (white ? d1 : d8);
            const Piece rook = make_piece(us, ROOK);
            sub[n_sub++] = {moving, from};
            add[n_add++] = {moving, king_to};
            sub[n_sub++] = {rook, rook_from};
            add[n_add++] = {rook, rook_to};
            break;
        }
        case EN_PASSANT: {
            Square captured = Square(us == WHITE ? to - 8 : to + 8);
            sub[n_sub++] = {moving, from};
            add[n_add++] = {moving, to};
            sub[n_sub++] = {make_piece(~us, PAWN), captured};
            break;
        }
        default: {
            Piece placed = moving;
            if ((flags >= PR_KNIGHT && flags <= PR_QUEEN) || flags >= PC_KNIGHT)
                placed = make_piece(us, PieceType(KNIGHT + (flags & 3)));
            sub[n_sub++] = {moving, from};
            add[n_add++] = {placed, to};
            if (flags & CAPTURE) sub[n_sub++] = {before.at(to), to};
            break;
        }
    }

    for (Color c: {WHITE, BLACK}) {
        const int16_t *src = parent.values[c];
        int16_t *dst = child.values[c];
        const int16_t *a0 = row(c, add[0].piece, add[0].square);
        const int16_t *s0 = row(c, sub[0].piece, sub[0].square);

        if (n_add == 1 && n_sub == 1) {
            for (int i = 0; i < HIDDEN; ++i) dst[i] = src[i] + a0[i] - s0[i];
        } else if (n_add == 1 && n_sub == 2) {
            const int16_t *s1 = row(c, sub[1].piece, sub[1].square);
            for (int i = 0; i < HIDDEN; ++i) dst[i] = src[i] + a0[i] - s0[i] - s1[i];
        } else {
            const int16_t *a1 = row(c, add[1].piece, add[1].square);
            const int16_t *s1 = row(c, sub[1].piece, sub[1].square);
            for (int i = 0; i < HIDDEN; ++i) dst[i] = src[i] + a0[i] + a1[i] - s0[i] - s1[i];
        }
    }
}

int evaluate(const Accumulator &acc, Color stm) {
    const int16_t *us = acc.values[stm];
    const int16_t *them = acc.values[~stm];
    const int16_t *w_us = net->output_weights;
    const int16_t *w_them = net->output_weights + HIDDEN;

    // SCReLU: clamp(x, 0, QA)^2. (c * w) fits in int16 because |w| <= 127, then widen for the second factor.
    int32_t sum = 0;
    for (int i = 0; i < HIDDEN; ++i) {
        int16_t c = std::clamp<int16_t>(us[i], 0, QA);
        sum += int32_t(int16_t(c * w_us[i])) * c;
    }
    for (int i = 0; i < HIDDEN; ++i) {
        int16_t c = std::clamp<int16_t>(them[i], 0, QA);
        sum += int32_t(int16_t(c * w_them[i])) * c;
    }
    return int((int64_t(sum) / QA + net->output_bias) * SCALE / (QA * QB));
}

int evaluate(const Position &p) {
    auto acc = std::make_unique<Accumulator>();
    refresh(*acc, p);
    return evaluate(*acc, p.turn());
}

} // namespace nnue
